### ISSUE TITLE
How to declare "declare const google;";

### ISSUE THREAD

**Issue by bellalMohamed** [BrunoAlencar/ionic3-google-maps-examples#1]
How can I do this step (declare const google;)

**Comment by fbiceo** [comment]
please reference example code 

[https://github.com/BrunoAlencar/ionic3-google-maps-examples/blob/master/src/pages/example-1/example-1.ts](https://github.com/BrunoAlencar/ionic3-google-maps-examples/blob/master/src/pages/example-1/example-1.ts)

**Comment by bellalMohamed** [comment]
oh I figured it out the same day but forgot to close the thread, anyway thanks for your attention :D
